name: go test

permissions:
  pull-requests: read
  contents: read

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  test:
    uses: go-openapi/ci-workflows/.github/workflows/go-test.yml@9e70984764198f45640ca9f0752a51a8ca159b99 # v0.1.2
    secrets: inherit
    steps:
      - name: Generate JUnit report safely
        run: |
          if [ -d "./reports" ] && [ "$(find ./reports -name '*.json' | wc -l)" -gt 0 ]; then
            find ./reports -name '*.json' -print0 | xargs -0 cat | go-junit-report > ./reports/junit_report.xml
          else
            mkdir -p ./reports
            echo "<testsuites></testsuites>" > ./reports/junit_report.xml
          fi
